# -*- coding: utf-8 -*-
import os
import re
import glob

# Translation map
translations = {
    "正在调用": "Calling",
    "获取账户余额": "get account balance",
    "调用失败": "call failed",
    "获取账户信息失败": "failed to get account info",
    "总净值": "total equity",
    "钱包": "wallet",
    "未实现": "unrealized",
    "可用": "available",
    "保证金占用": "margin used",
    "获取持仓失败": "failed to get positions",
    "杠杆已切换为": "leverage set to",
    "杠杆已是": "leverage is already",
    "无需切换": "no change needed",
    "等待": "Waiting",
    "秒冷却期": "second cooldown",
    "保证金模式已是": "margin mode is already",
    "保证金模式已切换为": "margin mode changed to",
    "取消旧委托单失败": "failed to cancel old orders",
    "可能没有委托单": "no orders may exist",
    "数量精度处理": "Quantity precision",
    "价格精度处理": "Price precision",
    "位有效数字": " significant figures",
    "开多仓成功": "Long position opened successfully",
    "开空仓成功": "Short position opened successfully",
    "平多仓成功": "Long position closed successfully",
    "平空仓成功": "Short position closed successfully",
    "订单": "Order",
    "开仓成功": "Position opened successfully",
    "平仓成功": "Position closed successfully",
    "设置止损失败": "Failed to set stop loss",
    "设置止盈失败": "Failed to set take profit",
    "取消挂单失败": "Failed to cancel pending orders",
    "已取消": "Cancelled",
    "的所有挂单": "'s all pending orders",
    "止损价设置": "Stop loss price set",
    "止盈价设置": "Take profit price set",
    "未找到": "Not found",
    "的精度信息": "'s precision info",
    "使用默认精度": "using default precision",
    "使用缓存的账户余额": "Using cached account balance",
    "缓存时间": "cache time",
    "秒前": "seconds ago",
    "缓存过期": "Cache expired",
    "获取持仓信息": "get position info",
    "使用缓存的持仓信息": "Using cached position info",
    "交易器初始化成功": "trader initialized successfully",
    "使用自定义AI API": "Using custom AI API",
    "模型": "model",
    "使用阿里云Qwen AI": "Using Alibaba Cloud Qwen AI",
    "使用DeepSeek AI": "Using DeepSeek AI",
    "使用币安合约交易": "Using Binance Futures",
    "使用Hyperliquid交易": "Using Hyperliquid",
    "使用Aster交易": "Using Aster",
    "驱动自动交易系统启动": "driven auto trading system started",
    "初始余额": "Initial balance",
    "扫描间隔": "Scan interval",
    "将全权决定杠杆": "will have full control over leverage",
    "仓位大小": "position size",
    "止损止盈等参数": "stop loss/take profit parameters",
    "执行失败": "Execution failed",
    "自动交易系统停止": "Auto trading system stopped",
    "决策周期": "Decision cycle",
    "风险控制": "Risk control",
    "暂停交易中": "trading paused",
    "剩余": "remaining",
    "分钟": "minutes",
    "日盈亏已重置": "Daily P&L reset",
    "账户净值": "Account equity",
    "账户": "Account",
    "持仓": "Positions",
    "正在请求AI分析并决策": "Requesting AI analysis and decision",
    "思维链分析": "Chain of Thought analysis",
    "错误情况": "error case",
    "决策列表": "Decision list",
    "杠杆": "Leverage",
    "仓位": "Position",
    "止损": "Stop loss",
    "止盈": "Take profit",
    "执行顺序": "Execution order",
    "已优化": "optimized",
    "先平仓": "close first",
    "后开仓": "open later",
    "执行决策失败": "Decision execution failed",
    "保存决策记录失败": "Failed to save decision record",
    "合并币种池": "Merging coin pool",
    "总计": "total",
    "个候选币种": "candidate coins",
    "分析历史表现失败": "Failed to analyze historical performance",
    "开多仓": "Open long",
    "开空仓": "Open short",
    "平多仓": "Close long",
    "平空仓": "Close short",
    "取消订单失败": "Failed to cancel order",
    "继续开仓": "continue opening position",
    "精度处理": "Precision handling",
    "价格": "price",
    "精度": "precision",
    "数量": "quantity",
    "获取到多仓数量": "Got long position quantity",
    "获取到空仓数量": "Got short position quantity",
    "已设置默认币种池": "Default coin pool set",
    "个币种": "coins",
    "已启用默认主流币种列表": "Default major coins list enabled",
    "未配置币种池API URL": "Coin pool API URL not configured",
    "使用默认主流币种列表": "using default major coins list",
    "次重试获取币种池": "retry fetching coin pool",
    "次重试成功": "retry succeeded",
    "保存币种池缓存失败": "Failed to save coin pool cache",
    "次请求失败": "request failed",
    "API请求全部失败": "All API requests failed",
    "尝试使用历史缓存数据": "trying to use historical cache data",
    "使用历史缓存数据": "Using historical cache data",
    "无法加载缓存数据": "Unable to load cache data",
    "最后错误": "last error",
    "正在请求": "Requesting",
    "币种池": "coin pool",
    "成功获取": "Successfully fetched",
    "已保存币种池缓存": "Coin pool cache saved",
    "缓存数据较旧": "Cache data is old",
    "小时前": "hours ago",
    "但仍可使用": "but still usable",
    "缓存数据时间": "Cache data time",
    "分钟前": "minutes ago",
    "未配置OI Top API URL": "OI Top API URL not configured",
    "跳过OI Top数据获取": "skipping OI Top data fetch",
    "次重试获取OI Top数据": "retry fetching OI Top data",
    "保存OI Top缓存失败": "Failed to save OI Top cache",
    "次请求OI Top失败": "OI Top request failed",
    "OI Top API请求全部失败": "All OI Top API requests failed",
    "使用历史OI Top缓存数据": "Using historical OI Top cache data",
    "无法加载OI Top缓存数据": "Unable to load OI Top cache data",
    "跳过OI Top数据": "skipping OI Top data",
    "正在请求OI Top数据": "Requesting OI Top data",
    "个OI Top币种": "OI Top coins",
    "时间范围": "time range",
    "已保存OI Top缓存": "OI Top cache saved",
    "OI Top缓存数据较旧": "OI Top cache data is old",
    "OI Top缓存数据时间": "OI Top cache data time",
    "获取AI500数据失败": "Failed to fetch AI500 data",
    "获取OI Top数据失败": "Failed to fetch OI Top data",
    "币种池合并完成": "Coin pool merge completed",
    "去重": "deduplicated",
    "已添加": "added",
    "启动所有Trader": "Starting all traders",
    "启动": "Starting",
    "运行错误": "runtime error",
    "停止所有Trader": "Stopping all traders",
    "持仓价值过低": "Position value too low",
    "跳过此币种": "skipping this coin",
    "持仓量": "position size",
    "收到账户信息请求": "Received account info request",
    "获取账户信息失败": "Failed to get account info",
    "返回账户信息": "Returning account info",
    "净值": "equity",
    "盈亏": "P&L",
    "API服务器启动在": "API server started at",
    "API文档": "API documentation",
    "竞赛总览": "Competition overview",
    "对比所有trader": "comparing all traders",
    "列表": "list",
    "指定trader的系统状态": "specified trader's system status",
    "指定trader的账户信息": "specified trader's account info",
    "指定trader的持仓列表": "specified trader's position list",
    "指定trader的决策日志": "specified trader's decision logs",
    "指定trader的最新决策": "specified trader's latest decision",
    "指定trader的统计信息": "specified trader's statistics",
    "指定trader的收益率历史数据": "specified trader's equity history",
    "指定trader的AI学习表现分析": "specified trader's AI learning performance analysis",
    "健康检查": "health check",
    "创建日志目录失败": "Failed to create log directory",
    "决策记录已保存": "Decision record saved",
    "删除旧记录失败": "Failed to delete old record",
    "已清理": "Cleaned up",
    "条旧记录": "old records",
    "天前": "days ago",
    "没有找到": "Not found",
    "的多仓": "'s long position",
    "的空仓": "'s short position",
    "信息为空": "info is empty",
    "共": "",
    "个": "",
    "第": "",
    "前": "top",
}

# Find all Go files
base_dir = r"c:\Users\Hill\Documents\nofx"
go_files = []
for root, dirs, files in os.walk(base_dir):
    for file in files:
        if file.endswith('.go'):
            go_files.append(os.path.join(root, file))

print(f"Found {len(go_files)} Go files")

# Process each file
for file_path in go_files:
    try:
        with open(file_path, 'r', encoding='utf-8') as f:
            content = f.read()
        
        # Check if file has Chinese characters
        if not re.search(r'[\u4e00-\u9fff]', content):
            continue
            
        print(f"Processing: {os.path.basename(file_path)}")
        
        # Apply translations (sort by length descending to replace longer phrases first)
        for chinese, english in sorted(translations.items(), key=lambda x: len(x[0]), reverse=True):
            content = content.replace(chinese, english)
        
        # Write back
        with open(file_path, 'w', encoding='utf-8') as f:
            f.write(content)
            
    except Exception as e:
        print(f"Error processing {file_path}: {e}")

print("Translation complete!")
