# -*- coding: utf-8 -*-
import os
import re

# Extended translation map for comments and remaining text
additional_translations = {
    "加载配置文件": "Load config file",
    "设置默认主流币种列表": "Set default major coins list",
    "设置是否使用默认主流币种": "Set whether to use default major coins",
    "设置币种池API URL": "Set coin pool API URL",
    "创建TraderManager": "Create TraderManager",
    "添加所有启用的trader": "Add all enabled traders",
    "跳过未启用的trader": "Skip disabled trader",
    "传递杠杆配置": "Pass leverage config",
    "传递Leverage配置": "Pass leverage config",
    "检查是否至少有一个启用的trader": "Check if at least one trader is enabled",
    "只显示启用的trader": "Show only enabled traders",
    "创建并启动API服务器": "Create and start API server",
    "创建并StartingAPI服务器": "Create and start API server",
    "设置优雅退出": "Set graceful shutdown",
    "启动所有trader": "Start all traders",
    "Starting所有trader": "Start all traders",
    "等待退出信号": "Wait for exit signal",
    "Waiting退出信号": "Wait for exit signal",
    "收到退出信号": "Received exit signal",
    "停止所有trader": "stopping all traders",
    "感谢使用AI交易竞赛系统": "Thank you for using AI Trading Competition System",
    "API服务器": "API server",
    "HTTP API服务器": "HTTP API server",
    "创建API服务器": "Create API server",
    "设置为Release模式": "Set to Release mode",
    "减少日志输出": "reduce log output",
    "启用CORS": "Enable CORS",
    "设置路由": "Setup routes",
    "CORS中间件": "CORS middleware",
    "解析私钥失败": "Failed to parse private key",
    "选择API URL": "Select API URL",
    "从私钥生成钱包地址": "Generate wallet address from private key",
    "无法转换公钥": "Cannot convert public key",
    "创建Exchange客户端": "Create Exchange client",
    "包含Info功能": "includes Info functionality",
    "获取meta信息": "Get meta info",
    "包含精度等配置": "includes precision config",
    "获取meta信息失败": "Failed to get meta info",
    "缓存meta信息": "Cache meta info",
    "包含精度等": "includes precision etc",
    "获取账户状态": "Get account status",
    "解析余额信息": "Parse balance info",
    "调试": "Debug",
    "打印API返回的完整CrossMarginSummary结构": "Print complete CrossMarginSummary structure from API",
    "关键修复": "Critical fix",
    "从所有持仓中累加真正的未实现盈亏": "Accumulate actual unrealized P&L from all positions",
    "正确理解Hyperliquid字段": "Correctly understand Hyperliquid fields",
    "总账户净值": "Total account equity",
    "已包含空闲资金": "includes idle funds",
    "持仓价值": "position value",
    "持仓占用的保证金": "margin used by positions",
    "已包含在AccountValue中": "included in AccountValue",
    "仅用于显示": "for display only",
    "为了兼容auto_trader.go的计算逻辑": "To be compatible with auto_trader.go calculation logic",
    "需要返回": "need to return",
    "不包含未实现盈亏的钱包余额": "wallet balance without unrealized P&L",
    "不含未实现盈亏": "without unrealized P&L",
    "遍历所有持仓": "Iterate through all positions",
    "持仓数量": "position quantity",
    "string类型": "string type",
    "跳过无持仓的": "skip empty positions",
    "标准化symbol格式": "Normalize symbol format",
    "使用如": "uses like",
    "我们转换为": "we convert to",
    "持仓数量和方向": "Position quantity and direction",
    "转为正数": "convert to positive",
    "价格信息": "Price info",
    "是指针类型": "is pointer type",
    "计算mark price": "Calculate mark price",
    "去掉USDT后缀": "remove USDT suffix",
    "调用UpdateLeverage": "Call UpdateLeverage",
    "false": "false",
    "逐仓模式": "Isolated margin mode",
    "设置杠杆失败": "Failed to set leverage",
    "先取消该币种的所有委托单": "First cancel all orders for this coin",
    "设置杠杆": "Set leverage",
    "格式": "format",
    "获取当前价格": "Get current price",
    "用于市价单": "for market orders",
    "关键": "Key",
    "根据币种精度要求": "According to coin precision requirements",
    "四舍五入数量": "Round quantity",
    "价格也需要处理为5位有效数字": "Price also needs 5 significant figures",
    "创建市价买入订单": "Create market buy order",
    "使用IOC limit order with aggressive price": "using IOC limit order with aggressive price",
    "类似市价单": "similar to market order",
    "使用四舍五入后的数量": "use rounded quantity",
    "使用处理后的价格": "use processed price",
    "开多仓失败": "Failed to open long",
    "Hyperliquid没有返回order ID": "Hyperliquid didn't return order ID",
    "创建市价卖出订单": "Create market sell order",
    "开空仓失败": "Failed to open short",
    "如果数量为0": "If quantity is 0",
    "获取当前持仓数量": "get current position quantity",
    "平仓订单": "close position order",
    "卖出": "sell",
    "ReduceOnly": "ReduceOnly",
    "只平仓": "close only",
    "不开新仓": "don't open new position",
    "平多仓失败": "Failed to close long",
    "平仓后取消该币种的所有挂单": "Cancel all pending orders after closing",
    "买入": "buy",
    "平空仓失败": "Failed to close short",
    "取消该币种的所有挂单": "Cancel all pending orders for this coin",
    "遍历所有委托单": "Iterate through all orders",
    "批量取消": "Batch cancel",
    "获取24小时ticker": "Get 24h ticker",
    "解析价格": "Parse price",
    "获取价格失败": "Failed to get price",
    "设置止损单": "Set stop loss order",
    "处理为5位有效数字": "Process to 5 significant figures",
    "创建止损单": "Create stop loss order",
    "止损买单": "stop loss buy",
    "触发价": "trigger price",
    "止损卖单": "stop loss sell",
    "设置止损失败": "Failed to set stop loss",
    "设置止盈单": "Set take profit order",
    "创建止盈单": "Create take profit order",
    "止盈卖单": "take profit sell",
    "止盈买单": "take profit buy",
    "设置止盈失败": "Failed to set take profit",
    "如果meta信息为空": "If meta info is empty",
    "使用默认精度4": "using default precision 4",
    "遍历meta.universe找到对应的币种": "Iterate through meta.universe to find corresponding coin",
    "格式化数量到正确的精度": "Format quantity to correct precision",
    "解析精度": "Parse precision",
    "币安配置": "Binance config",
    "Hyperliquid配置": "Hyperliquid config",
    "Aster配置": "Aster config",
    "Aster主钱包地址": "Aster main wallet address",
    "Aster API钱包地址": "Aster API wallet address",
    "Aster API钱包私钥": "Aster API wallet private key",
    "AI配置": "AI config",
    "自定义AI API配置": "Custom AI API config",
    "支持任何OpenAI格式的API": "supports any OpenAI format API",
    "杠杆配置": "Leverage config",
    "BTC和ETH的杠杆倍数": "Leverage for BTC and ETH",
    "主账户建议": "main account recommended",
    "子账户": "sub-account",
    "山寨币的杠杆倍数": "Leverage for altcoins",
    "总配置": "Main config",
    "是否使用默认主流币种列表": "Whether to use default major coins list",
    "默认主流币种池": "Default major coin pool",
    "从文件加载配置": "Load config from file",
    "读取配置文件失败": "Failed to read config file",
    "解析配置文件失败": "Failed to parse config file",
    "设置默认值": "Set default values",
    "如果use_default_coins未设置": "If use_default_coins is not set",
    "为false": "is false",
    "且没有配置coin_pool_api_url": "and coin_pool_api_url is not configured",
    "则默认使用默认币种列表": "then use default coin list by default",
    "设置默认币种池": "Set default coin pool",
    "验证配置": "Validate config",
    "配置验证失败": "Config validation failed",
    "验证配置有效性": "Validate config validity",
    "至少需要配置一个trader": "At least one trader must be configured",
    "ID不能为空": "ID cannot be empty",
    "重复": "duplicate",
    "Name不能为空": "Name cannot be empty",
    "ai_model必须是": "ai_model must be",
    "验证交易平台配置": "Validate exchange config",
    "默认使用币安": "default to Binance",
    "exchange必须是": "exchange must be",
    "根据平台验证对应的密钥": "Validate corresponding keys for platform",
    "使用币安时必须配置binance_api_key和binance_secret_key": "When using Binance must configure binance_api_key and binance_secret_key",
    "使用Hyperliquid时必须配置hyperliquid_private_key": "When using Hyperliquid must configure hyperliquid_private_key",
    "使用Aster时必须配置aster_user": "When using Aster must configure aster_user",
    "使用Qwen时必须配置qwen_key": "When using Qwen must configure qwen_key",
    "使用DeepSeek时必须配置deepseek_key": "When using DeepSeek must configure deepseek_key",
    "使用自定义API时必须配置custom_api_url": "When using custom API must configure custom_api_url",
    "使用自定义API时必须配置custom_api_key": "When using custom API must configure custom_api_key",
    "使用自定义API时必须配置custom_model_name": "When using custom API must configure custom_model_name",
    "initial_balance必须大于0": "initial_balance must be greater than 0",
    "默认3分钟": "default 3 minutes",
    "默认8080端口": "default port 8080",
    "设置杠杆默认值": "Set leverage default values",
    "适配币安子账户限制": "adapt to Binance sub-account limits",
    "最大5倍": "max 5x",
    "默认5倍": "default 5x",
    "安全值": "safe value",
    "适配子账户": "adapt to sub-account",
    "获取扫描间隔": "Get scan interval",
    "交易器统一接口": "Unified trader interface",
    "支持多个交易平台": "Support multiple trading platforms",
    "Hyperliquid等": "Hyperliquid etc",
    "平仓": "close position",
    "quantity=0表示全部平仓": "quantity=0 means close all",
    "API提供商类型": "AI provider type",
    "阿里云需要": "Alibaba Cloud needs",
    "是否使用完整URL": "Whether to use full URL",
    "不添加": "don't add",
    "默认配置": "Default config",
    "增加到120秒": "Increase to 120 seconds",
    "因为AI需要分析大量数据": "because AI needs to analyze large amounts of data",
    "设置DeepSeek API密钥": "Set DeepSeek API key",
    "设置阿里云Qwen API密钥": "Set Alibaba Cloud Qwen API key",
    "可选": "optional",
    "设置自定义OpenAI兼容API": "Set custom OpenAI compatible API",
    "检查URL是否以#结尾": "Check if URL ends with #",
    "如果是则使用完整URL": "if yes then use full URL",
    "设置完整的AI配置": "Set complete AI config",
    "高级用户": "advanced users",
    "使用 system": "Using system",
    "调用AI API": "call AI API",
    "推荐": "recommended",
    "AI API密钥未设置": "AI API key not set",
    "请先调用": "please call first",
    "重试配置": "Retry config",
    "如果不是网络错误": "If not network error",
    "不重试": "don't retry",
    "重试前等待": "Wait before retry",
    "单次调用AI API": "Single call to AI API",
    "内部使用": "internal use",
    "构建 messages 数组": "Build messages array",
    "如果有 system prompt": "If has system prompt",
    "添加 system message": "add system message",
    "添加 user message": "add user message",
    "构建请求体": "Build request body",
    "降低temperature以提高JSON格式稳定性": "Lower temperature to improve JSON format stability",
    "注意": "Note",
    "response_format 参数仅 OpenAI 支持": "response_format parameter only supported by OpenAI",
    "DeepSeek": "DeepSeek",
    "Qwen 不支持": "Qwen not supported",
    "我们通过强化 prompt 和后处理来确保 JSON 格式正确": "We ensure JSON format through enhanced prompt and post-processing",
    "序列化请求失败": "Failed to serialize request",
    "创建HTTP请求": "Create HTTP request",
    "使用完整URL": "Use full URL",
    "默认行为": "Default behavior",
    "创建请求失败": "Failed to create request",
    "根据不同的Provider设置认证方式": "Set authentication based on different Provider",
    "阿里云Qwen使用API-Key认证": "Alibaba Cloud Qwen uses API-Key authentication",
    "如果使用的不是兼容模式": "If not using compatible mode",
    "可能需要不同的认证方式": "may need different authentication",
    "发送请求": "Send request",
    "发送请求失败": "Failed to send request",
    "读取响应": "Read response",
    "读取响应失败": "Failed to read response",
    "API返回错误": "API returned error",
    "解析响应": "Parse response",
    "解析响应失败": "Failed to parse response",
    "API返回空响应": "API returned empty response",
    "判断错误是否可重试": "Check if error is retryable",
    "网络错误": "Network error",
    "超时": "timeout",
    "EOF等可以重试": "EOF etc can retry",
    "决策记录": "Decision record",
    "决策时间": "decision time",
    "周期编号": "cycle number",
    "发送给AI的输入prompt": "input prompt sent to AI",
    "AI思维链": "AI chain of thought",
    "输出": "output",
    "决策JSON": "decision JSON",
    "账户状态快照": "account state snapshot",
    "持仓快照": "position snapshot",
    "候选币种列表": "candidate coins list",
    "执行的决策": "executed decisions",
    "执行日志": "execution log",
    "是否成功": "whether successful",
    "错误信息": "error message",
    "如果有": "if any",
    "决策动作": "decision action",
    "币种": "coin",
    "开仓时": "when opening",
    "执行价格": "execution price",
    "执行时间": "execution time",
    "决策日志记录器": "decision logger",
    "创建决策日志记录器": "Create decision logger",
    "确保日志目录存在": "Ensure log directory exists",
    "记录决策": "Log decision",
    "生成文件名": "Generate filename",
    "序列化为JSON": "Serialize to JSON",
    "带缩进": "with indentation",
    "方便阅读": "for readability",
    "写入文件": "Write to file",
    "写入决策记录失败": "Failed to write decision record",
    "获取最近N条记录": "Get latest N records",
    "按时间正序": "in chronological order",
    "从旧到新": "from old to new",
    "读取日志目录失败": "Failed to read log directory",
    "先按修改时间倒序收集": "First collect in reverse order by modified time",
    "最新的在前": "newest first",
    "反转数组": "Reverse array",
    "让时间从旧到新排列": "order from old to new",
    "用于图表显示": "for chart display",
    "获取指定日期的所有记录": "Get all records for specified date",
    "查找日志文件失败": "Failed to find log files",
    "清理N天前的旧记录": "Clean old records from N days ago",
    "获取统计信息": "Get statistics",
    "统计信息": "Statistics",
    "单笔交易结果": "Single trade outcome",
    "杠杆倍数": "leverage multiplier",
    "开仓价": "open price",
    "平仓价": "close price",
    "保证金使用": "margin used",
    "盈亏百分比": "P&L percentage",
    "相对保证金": "relative to margin",
    "持仓时长": "position duration",
    "开仓时间": "open time",
    "平仓时间": "close time",
    "是否止损": "whether stop loss",
    "交易表现分析": "Trading performance analysis",
    "总交易数": "total trades",
    "盈利交易数": "winning trades",
    "亏损交易数": "losing trades",
    "胜率": "win rate",
    "平均盈利": "average win",
    "平均亏损": "average loss",
    "盈亏比": "profit factor",
    "夏普比率": "Sharpe ratio",
    "风险调整后收益": "risk-adjusted return",
    "最近N笔交易": "recent N trades",
    "各币种表现": "performance by coin",
    "表现最好的币种": "best performing coin",
    "表现最差的币种": "worst performing coin",
    "币种表现统计": "Coin performance statistics",
    "交易次数": "trade count",
    "盈利次数": "win count",
    "亏损次数": "loss count",
    "总盈亏": "total P&L",
    "平均盈亏": "average P&L",
    "分析最近N个周期的交易表现": "Analyze trading performance for recent N cycles",
    "读取历史记录失败": "Failed to read historical records",
    "追踪持仓状态": "Track position state",
    "为了避免开仓记录在窗口外导致匹配失败": "To avoid matching failure when open records are outside window",
    "需要先从所有历史记录中找出未平仓的持仓": "need to find unclosed positions from all historical records first",
    "获取更多历史记录来构建完整的持仓状态": "Get more historical records to build complete position state",
    "使用更大的窗口": "using larger window",
    "扩大3倍窗口": "expand window by 3x",
    "先从扩大的窗口中收集所有开仓记录": "First collect all open records from expanded window",
    "记录开仓": "Record opening",
    "移除已平仓记录": "Remove closed records",
    "遍历分析窗口内的记录": "Iterate through records in analysis window",
    "生成交易结果": "generate trade outcomes",
    "使用symbol_side作为key": "use symbol_side as key",
    "区分多空持仓": "distinguish long/short positions",
    "更新开仓记录": "Update open record",
    "可能已经在预填充时记录过了": "may have been recorded during pre-filling",
    "查找对应的开仓记录": "Find corresponding open record",
    "可能来自预填充或当前窗口": "may be from pre-filling or current window",
    "计算实际盈亏": "Calculate actual P&L",
    "合约交易 PnL 计算": "Futures PnL calculation",
    "杠杆不影响绝对盈亏": "Leverage doesn't affect absolute P&L",
    "只影响保证金需求": "only affects margin requirements",
    "计算盈亏百分比": "Calculate P&L percentage",
    "记录交易结果": "Record trade outcome",
    "分类交易": "Classify trade",
    "持平": "break even",
    "避免将pnl=0算入亏损": "avoid counting pnl=0 as loss",
    "的交易不计入盈利也不计入亏损": "trades neither count as win nor loss",
    "但计入总交易数": "but count in total trades",
    "更新币种统计": "Update coin statistics",
    "计算统计指标": "Calculate statistics",
    "计算总盈利和总亏损": "Calculate total profit and total loss",
    "当前是累加的总和": "currently accumulated sum",
    "负数": "negative number",
    "绝对值": "absolute value",
    "取负号得到绝对值": "negate to get absolute value",
    "只有盈利没有亏损的情况": "Only profit no loss case",
    "设置为一个很大的值表示完美策略": "set to a large value to indicate perfect strategy",
    "计算各币种胜率和平均盈亏": "Calculate win rate and average P&L by coin",
    "只保留最近的交易": "Keep only recent trades",
    "倒序": "reverse order",
    "最新的在前": "newest first",
    "让最新的在前": "put newest first",
    "计算夏普比率": "Calculate Sharpe ratio",
    "需要至少2个数据点": "needs at least 2 data points",
    "基于账户净值的变化计算风险调整后收益": "Calculate risk-adjusted return based on account equity changes",
    "提取每个周期的账户净值": "Extract account equity for each cycle",
    "TotalBalance字段实际存储的是TotalEquity": "TotalBalance field actually stores TotalEquity",
    "账户总净值": "total account equity",
    "TotalUnrealizedProfit字段实际存储的是TotalPnL": "TotalUnrealizedProfit field actually stores TotalPnL",
    "相对初始余额的盈亏": "P&L relative to initial balance",
    "直接使用TotalBalance": "directly use TotalBalance",
    "因为它已经是完整的账户净值": "because it's already the complete account equity",
    "计算周期收益率": "Calculate period returns",
    "period returns": "period returns",
    "计算平均收益率": "Calculate average return",
    "计算收益率标准差": "Calculate return standard deviation",
    "避免除以零": "Avoid division by zero",
    "无波动的正收益": "no volatility positive return",
    "无波动的负收益": "no volatility negative return",
    "假设无风险利率为0": "assume risk-free rate is 0",
    "直接返回周期级别的夏普比率": "directly return period-level Sharpe ratio",
    "非年化": "not annualized",
    "正常范围": "normal range",
    "单个trader的配置": "Single trader config",
    "是否启用该trader": "whether to enable this trader",
    "交易平台选择": "Trading platform selection",
    "二选一": "choose one",
}

# Find all Go files
base_dir = r"c:\Users\Hill\Documents\nofx"
go_files = []
for root, dirs, files in os.walk(base_dir):
    for file in files:
        if file.endswith('.go'):
            go_files.append(os.path.join(root, file))

print(f"Found {len(go_files)} Go files")

# Process each file
for file_path in go_files:
    try:
        with open(file_path, 'r', encoding='utf-8') as f:
            content = f.read()
        
        # Check if file has Chinese characters
        if not re.search(r'[\u4e00-\u9fff]', content):
            continue
            
        print(f"Processing: {os.path.basename(file_path)}")
        
        # Apply translations (sort by length descending to replace longer phrases first)
        for chinese, english in sorted(additional_translations.items(), key=lambda x: len(x[0]), reverse=True):
            content = content.replace(chinese, english)
        
        # Write back
        with open(file_path, 'w', encoding='utf-8') as f:
            f.write(content)
            
    except Exception as e:
        print(f"Error processing {file_path}: {e}")

print("Additional translation complete!")
